//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountEntry
    {
        public AccountEntry()
        {
            this.VoucherEntries = new HashSet<VoucherEntry>();
            this.SalesInvoiceEntries = new HashSet<SalesInvoiceEntry>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public int Type { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> AccountEntryTypeID { get; set; }
    
        public virtual ICollection<VoucherEntry> VoucherEntries { get; set; }
        public virtual ICollection<SalesInvoiceEntry> SalesInvoiceEntries { get; set; }
        public virtual AccountEntryType AccountEntryType { get; set; }
    }
}
