//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payee
    {
        public Payee()
        {
            this.Vouchers = new HashSet<Voucher>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Address { get; set; }
        public string TIN { get; set; }
    
        public virtual ICollection<Voucher> Vouchers { get; set; }
    }
}
