//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Vouchers = new HashSet<Voucher>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
            this.SalesInvoiceEntries = new HashSet<SalesInvoiceEntry>();
            this.VoucherEntries = new HashSet<VoucherEntry>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal ContractAmount { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<Voucher> Vouchers { get; set; }
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        public virtual ICollection<SalesInvoiceEntry> SalesInvoiceEntries { get; set; }
        public virtual ICollection<VoucherEntry> VoucherEntries { get; set; }
    }
}
