//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int ID { get; set; }
        public int Role { get; set; }
        public int ActionRouteID { get; set; }
    
        public virtual ActionRoute ActionRoute { get; set; }
    }
}
