//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesInvoiceEntry
    {
        public int ID { get; set; }
        public int SalesInvoiceID { get; set; }
        public int Quantity { get; set; }
        public string Unit { get; set; }
        public string Articles { get; set; }
        public decimal UnitPrice { get; set; }
        public int AddedbyID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> AccountEntryID { get; set; }
    
        public virtual SalesInvoice SalesInvoice { get; set; }
        public virtual User User { get; set; }
        public virtual Project Project { get; set; }
        public virtual AccountEntry AccountEntry { get; set; }
    }
}
