//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherEntry
    {
        public int ID { get; set; }
        public int VoucherID { get; set; }
        public int AccountEntryID { get; set; }
        public Nullable<int> BankID { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public int AddedByID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual AccountEntry AccountEntry { get; set; }
        public virtual User User { get; set; }
        public virtual Voucher Voucher { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Project Project { get; set; }
    }
}
